# Generated by Django 3.2.12 on 2023-05-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('short_description', models.TextField(blank=True, max_length=160)),
                ('long_description', models.TextField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
    ]
