# Generated by Django 4.2 on 2023-04-27 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_last', models.CharField(max_length=30)),
                ('short_description', models.CharField(max_length=160)),
                ('long_description', models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_last', models.CharField(max_length=30)),
                ('short_description', models.CharField(max_length=160)),
                ('long_description', models.CharField(max_length=450)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=160)),
                ('body', models.CharField(max_length=2000)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.writer')),
            ],
        ),
    ]
