# Generated by Django 4.2 on 2023-05-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='approve',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='approve',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date_published',
        ),
        migrations.AlterField(
            model_name='article',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
